USE FoodService;

CREATE TABLE TypeOfFood(
TypeOfFoodId INT PRIMARY KEY,
Name VARCHAR(50),
[Image] VARBINARY)

CREATE TABLE FoodItem(
FoodItemId INT PRIMARY KEY,
TypeOfFoodIdRef INT NOT NULL FOREIGN KEY REFERENCES TypeOfFood(TypeOfFoodId),
Name VARCHAR(50) NOT NULL,
Weight DECIMAL(5, 2) NOT NULL,
Price DECIMAL(4, 2) NOT NULL,
Description VARCHAR(100)
)

CREATE TABLE OrderItem(
OrderItemId INT PRIMARY KEY,
FoodItemIdRef INT NOT NULL FOREIGN KEY REFERENCES FoodItem(FoodItemId),
)


CREATE TABLE Customer(
CustomerId INT PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Email VARCHAR(30) NOT NULL
)

CREATE TABLE Employee(
EmployeeId INT PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Email VARCHAR(30) NOT NULL
)

CREATE TABLE Payment(
PaymentId INT PRIMARY KEY,
Code CHAR(3) NOT NULL UNIQUE,
Name VARCHAR(30) NOT NULL
)

CREATE TABLE [Order](
OrderId INT PRIMARY KEY,
CustomerIdRef INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerId),
EmployeeRef INT NOT NULL FOREIGN KEY REFERENCES Employee(EmployeeId),
PaymentIdRef INT NOT NULL FOREIGN KEY REFERENCES Payment(PaymentId),
Timestamp DATETIME NOT NULL,
Description VARCHAR(100)
)
